### ISSUE TITLE
Why the sensor value was null when I  used "TemperatureAlertSystem.Domain.dll" in a console program.

### ISSUE THREAD

**Issue by rogerluo410** [tommasobertoni/HardwareMonitor#1]
Hi, dear author, 

I didn't use the UI program created by you, otherwise,  created a console program to include the "TemperatureAlertSystem.Domain.dll" . 

However, when I tested the code, found that the the value of ISensor object was null ,but in your UI program was ok. 

```
// here, sensor.Value is null  in CpuSensorsFilter.cs
foreach (var sensor in cpuSensors)
                    if (sensor.SensorType == requestedSensorType)
                        requestedSensors.Add(sensor);
```

I don't know why the problem occurred and how to solve it.  I think it may be something about configuring action. 

Could you please give me a little bit of hint !  Did you do some special things in your UI program "TemperatureAlertSystem.TrayUI".

Thank you in advance!

**Comment by rogerluo410** [comment]
It's ok when I run the console program as administrator. 
Thank you anyway.

**Comment by tommasobertoni** [comment]
Yes, as the [official website](http://openhardwaremonitor.org/downloads/) says: "Without Administrator rights most hardware sensors are not accessible".<br/>As you can see in the _tsa.manifest_ file, the UI application requires administrator privileges.
